services:
  db:
    image: pgvector/pgvector:pg15
    container_name: my_vector_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: readsync
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
